export const skillsConstant = [
  {
    btnText: "Programming Languages",
    cardTitle: "@ Programming Languages",
    technology: [
      { name: "JavaScript", icon: "/tech-icons/JavaScript.svg" },
      { name: "TypeScript", icon: "/tech-icons/TypeScript.svg" },
      { name: "HTML", icon: "/tech-icons/HTML5.svg" },
      { name: "CSS", icon: "/tech-icons/CSS3.svg" },
    ],
    identifier: "ProgrammingLanguages",
  },
  {
    btnText: "Front-End Technologies",
    cardTitle: "@ Front-End Technologies",
    technology: [
      { name: "React JS", icon: "/tech-icons/React.svg" },
      { name: "Next JS", icon: "/tech-icons/Next.js.svg" },
      { name: "Redux", icon: "/tech-icons/Redux.svg" },
      { name: "Tailwind CSS", icon: "/tech-icons/Tailwind-CSS.svg" },
      { name: "Styled Components", icon: "/tech-icons/styled-components.svg" },
      { name: "Material UI", icon: "/tech-icons/Material-UI.svg" },
      { name: "shadcn/ui", icon: "/tech-icons/Shadcn-ui.svg" },
      { name: "Framer Motion", icon: "/tech-icons/Framer-motion.svg" },
      { name: "Swiper", icon: "/tech-icons/Swiper.svg" },
      { name: "DND/KIT", icon: "/tech-icons/dnd-kit.svg" },
    ],
    identifier: "FrontEndTechnologies",
  },
  {
    btnText: "Back-End Technologies",
    cardTitle: "@ Back-End Technologies",
    technology: [
      { name: "Node JS", icon: "/tech-icons/Node.js.svg" },
      { name: "Express JS", icon: "/tech-icons/Express.svg" },
      { name: "Socket.io", icon: "/tech-icons/Socket.io.svg" },
      { name: "Sanity", icon: "/tech-icons/Sanity.svg" },
      { name: "Prisma", icon: "/tech-icons/prisma.svg" },
      { name: "Handlebars", icon: "/tech-icons/Handlebars.svg" },
    ],
    identifier: "BackEndTechnologies",
  },
  {
    btnText: "Database",
    cardTitle: "@ Database",
    technology: [
      { name: "MongoDB", icon: "/tech-icons/MongoDB.svg" },
      { name: "PostgresSQL", icon: "/tech-icons/PostgresSQL.svg" },
      { name: "Redis", icon: "/tech-icons/Redis.svg" },
    ],
    identifier: "Database",
  },
  {
    btnText: "Tools & Platforms",
    cardTitle: "@ Tools & Platforms",
    technology: [
      { name: "Git", icon: "/tech-icons/Git.svg" },
      { name: "GitHub", icon: "/tech-icons/GitHub.svg" },
      { name: "Docker", icon: "/tech-icons/Docker.svg" },
      { name: "Postman", icon: "/tech-icons/Postman.svg" },
      { name: "Vite", icon: "/tech-icons/Vite.js.svg" },
      { name: "Vercel", icon: "/tech-icons/Vercel.svg" },
      { name: "Cloudinary", icon: "/tech-icons/Cloudinary.svg" },
      { name: "Stripe", icon: "/tech-icons/Stripe-icon.svg" },
      { name: "Appwrite", icon: "/tech-icons/Appwrite.svg" },
      { name: "Render", icon: "/tech-icons/Render.svg" },
      { name: "Clerk", icon: "/tech-icons/clerk.svg" },
      { name: "Vimeo", icon: "/tech-icons/Vimeo.svg" },
    ],
    identifier: "Tools&Platforms",
  },
];
